# Project information
site_name: Google Cloud HSM
site_description: Cloud HSM to sign Web3.py Ethereum transactions
site_author: Saikat K
site_url: https://github.com/Ankvik-Tech-Labs/google-cloud-hsm
copyright: 'Copyright &copy; Saikat K 2024-present'

# Repository
repo_url: https://github.com/Ankvik-Tech-Labs/google-cloud-hsm
repo_name: Ankvik-Tech-Labs/google-cloud-hsm

theme:
    name: material
    font:
        text: Roboto
        code: Roboto Mono
    icon:
        logo: material/library
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: teal
          accent: light blue
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: teal
          accent: light blue
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google
    - gen-files:
        scripts:
            - docs/scripts/gen_ref_nav.py

watch:
    - docs
    - google_cloud_hsm

# Navigation
nav:
    - Home:
        - About: index.md
        - Changelog: changelog.md
        - License: license.md
        - Authors: authors.md
        - Contributing: contributing.md
    - Reference:
        - google_cloud_hsm: reference/google_cloud_hsm.md
